---
apiVersion: v1
kind: Service
metadata:
  name: beacon-api
spec:
  selector:
    app: beacon-api
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
