# Shrink default JVM heap.
esJavaOpts: '-Xmx128m -Xms128m'

# Allocate smaller chunks of memory per pod.
esResources:
  requests:
    cpu: '100m'
    memory: '512M'
  limits:
    cpu: '1000m'
    memory: '512M'

storageClassName: 'standard'
