---
postgresqlUsername: postgres
postgresqlPassword: postgres

resources:
  requests:
    cpu: 100m
    memory: 100Mi

postgresqlExtendedConf:
  shared_preload_libraries: 'pg_stat_statements'
  pg_stat_statements.max: 10000
  pg_stat_statements.track: all

primary:
  podAnnotations:
    prometheus.io/scrape: 'true' ## TODO: this is scraping potgres container as well (which obviously fails)
  extraVolumes:
    - name: config
      configMap:
        name: postgres-exporter-configmap
  sidecars:
    - name: postgres-exporter
      image: wrouesnel/postgres_exporter:v0.8.0
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 100Mi
      ports:
        - containerPort: 9187
          name: metrics
          protocol: TCP
      volumeMounts:
        - name: config
          readOnly: true
          mountPath: /config
      env:
        - name: PG_EXPORTER_EXTEND_QUERY_PATH
          value: /config/queries.yaml
        - name: PG_EXPORTER_AUTO_DISCOVER_DATABASES
          value: 'true'
        - name: DATA_SOURCE_URI
          value: postgres-postgresql?sslmode=disable
        - name: DATA_SOURCE_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: username
        - name: DATA_SOURCE_PASS
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password
