---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-indexer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-indexer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: search-indexer
        team: beacon
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - image: insightio/search-indexer
          imagePullPolicy: Always
          name: search-indexer
          env:
            - name: JAEGER_AGENT_HOST
              value: jaeger-agent.monitoring:6831
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: PLAINTEXT://kafka:9092
            - name: ELASTICSEARCH_HOSTS
              value: elasticsearch-master:9200
          resources:
            requests:
              cpu: 100m
              memory: 400Mi
            limits:
              cpu: 100m
              memory: 400Mi
