---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: accounts
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: accounts
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
