---
extends: default
rules:
  truthy:
    allowed-values: ['true', 'false', 'on']
  line-length: disable
ignore: |
  helmfile.yaml
  infrastructure/k8/development/releases/*
  infrastructure/k8/development/letsencrypt/**
