coverage:
  status:
    project:
      default:
        target: auto
      backend:
        target: auto
        flags:
          - backend
      frontend:
        target: auto
        flags:
          - frontend
