---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend/k8/base
  - frontend/k8/base

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: search-indexer
    path: image-pull-secret.patch
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: auth-api
    path: image-pull-secret.patch
  - target:
      group: batch
      version: v1
      kind: Job
      name: auth-api-postgres-migrations
    path: image-pull-secret.patch
  - target:
      group: batch
      version: v1
      kind: Job
      name: auth-api-postgres-migrations
    path: job-generate-name.patch
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: session-api
    path: image-pull-secret.patch
  - target:
      group: batch
      version: v1
      kind: Job
      name: session-api-postgres-migrations
    path: image-pull-secret.patch
  - target:
      group: batch
      version: v1
      kind: Job
      name: session-api-postgres-migrations
    path: job-generate-name.patch
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: beacon-api
    path: image-pull-secret.patch
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: app
    path: image-pull-secret.patch
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: try
    path: image-pull-secret.patch
