---
apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: insight
build:
  local:
    useBuildkit: true
    concurrency: 3
  tagPolicy:
    gitCommit:
      variant: CommitSha
  artifacts:
    - image: insightio/frontend-app
      context: .
      docker:
        dockerfile: frontend/app/docker/Dockerfile
    - image: insightio/frontend-try
      context: .
      docker:
        dockerfile: frontend/try/docker/Dockerfile
    - image: insightio/session-api
      context: backend
      custom:
        dependencies:
          dockerfile:
            path: session/session-api/docker/Dockerfile.jvm
        buildCommand: ./custom_build.sh session/session-api/docker/Dockerfile.jvm
    - image: insightio/auth-api
      context: backend
      custom:
        dependencies:
          dockerfile:
            path: auth/auth-api/docker/Dockerfile.jvm
        buildCommand: ./custom_build.sh auth/auth-api/docker/Dockerfile.jvm
    - image: insightio/auth-api-postgres-migrations
      context: backend/auth/auth-api/migrations/postgres
    - image: insightio/billing-api
      context: backend
      custom:
        dependencies:
          dockerfile:
            path: billing/billing-api/docker/Dockerfile.jvm
        buildCommand: ./custom_build.sh billing/billing-api/docker/Dockerfile.jvm
    - image: insightio/billing-api-postgres-migrations
      context: backend/billing/billing-api/migrations/postgres
    - image: insightio/beacon-api
      context: backend
      custom:
        dependencies:
          dockerfile:
            path: beacon/beacon-api/docker/Dockerfile.jvm
        buildCommand: ./custom_build.sh beacon/beacon-api/docker/Dockerfile.jvm
    - image: insightio/search-indexer
      context: backend
      custom:
        dependencies:
          dockerfile:
            path: events/search-indexer/docker/Dockerfile.jvm
        buildCommand: ./custom_build.sh events/search-indexer/docker/Dockerfile.jvm
    - image: insightio/session-api-postgres-migrations
      context: backend/session/session-api/migrations/postgres
deploy:
  kustomize:
    paths:
      - .
profiles:
  - name: push
    build:
      local:
        push: true
    patches:
      - op: add
        path: /build/artifacts/0/docker/buildArgs
        value:
          billing_api_base_url: https://billing-api.dev.snuderls.eu
          session_api_base_url: https://session-api.dev.snuderls.eu
          auth_api_base_url: https://auth-api.dev.snuderls.eu
          try_base_url: https://try.dev.snuderls.eu
      - op: add
        path: /build/artifacts/1/docker/buildArgs
        value:
          auth_api_base_url: https://auth-api.dev.snuderls.eu
          app_base_url: https://app.dev.snuderls.eu
