---
apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: insight
build:
  local:
    useBuildkit: true
    concurrency: 3
  tagPolicy:
    gitCommit:
      variant: CommitSha
  artifacts:
    - image: insightio/frontend-homepage
      context: .
      docker:
        dockerfile: frontend/homepage/docker/Dockerfile
    - image: insightio/frontend-app
      context: .
      docker:
        dockerfile: frontend/app/docker/Dockerfile
    - image: insightio/frontend-accounts
      context: .
      docker:
        dockerfile: frontend/accounts/docker/Dockerfile
    - image: insightio/session-api
      context: backend
      custom:
        dependencies:
          dockerfile:
            path: session/session-api/docker/Dockerfile.jvm
        buildCommand: ./custom_build.sh session/session-api/docker/Dockerfile.jvm
    - image: insightio/auth-api
      context: backend
      custom:
        dependencies:
          dockerfile:
            path: auth/auth-api/docker/Dockerfile.jvm
        buildCommand: ./custom_build.sh auth/auth-api/docker/Dockerfile.jvm
    - image: insightio/auth-api-postgres-migrations
      context: backend/auth/auth-api/migrations/postgres
    - image: insightio/kafka-migrations
      context: infrastructure/kafka
    - image: insightio/billing-api
      context: backend
      custom:
        dependencies:
          dockerfile:
            path: billing/billing-api/docker/Dockerfile.jvm
        buildCommand: ./custom_build.sh billing/billing-api/docker/Dockerfile.jvm
    - image: insightio/billing-api-postgres-migrations
      context: backend/billing/billing-api/migrations/postgres
    - image: insightio/beacon-api
      context: backend
      custom:
        dependencies:
          dockerfile:
            path: beacon/beacon-api/docker/Dockerfile.jvm
        buildCommand: ./custom_build.sh beacon/beacon-api/docker/Dockerfile.jvm
    - image: insightio/search-indexer
      context: backend
      custom:
        dependencies:
          dockerfile:
            path: events/search-indexer/docker/Dockerfile.jvm
        buildCommand: ./custom_build.sh events/search-indexer/docker/Dockerfile.jvm
    - image: insightio/session-api-postgres-migrations
      context: backend/session/session-api/migrations/postgres
deploy:
  kustomize:
    paths:
      - .
profiles:
  - name: push
    build:
      local:
        push: true
