---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: auth-api
  namespace: auth
  labels:
    team: auth
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth-api
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
