---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    email: { { .Values.email } }
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt

    solvers:
      - dns01:
          route53:
            region: { { .Values.region } }
            hostedZoneID: { { .Values.hostedZoneID } }
            accessKeyID: { { .Values.accessKeyID } }
            secretAccessKeySecretRef:
              name: { { .Values.secretAccessKeySecretName } }
              key: { { .Values.secretAccessKeySecretKey } }
        selector:
          dnsZones: { { .Values.dnsZones } }
