---
dnsZones:
  - rebrowse.dev

region: us-east-1
hostedZoneID: Z082926732A4WWMKU2W2Q
accessKeyID: AKIA2L6OVXLRCRBVSSVN

# Credentials
secretAccessKeySecretName: acme-credentials-route53
secretAccessKeySecretKey: secret-access-key
