---
# Permit co-located instances for solitary minikube virtual machines.
antiAffinity: 'soft'

# Shrink default JVM heap.
esJavaOpts: '-Xmx128m -Xms128m'

# Allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: '100m'
    memory: '512M'
  limits:
    cpu: '1000m'
    memory: '512M'

# Request smaller persistent volumes.
volumeClaimTemplate:
  accessModes: ['ReadWriteOnce']
  storageClassName: 'local-path'
  resources:
    requests:
      storage: 1000M

replicas: 1

# If running only 1 master node will be in state yellow after restart, since it wont be able to do a clean handoff from prev master
clusterHealthCheckParams: wait_for_status=yellow&timeout=1s
