---
backend:
  type: es
  es:
    time_key: '@time'

parsers:
  enabled: true
  regex:
    - name: cri-2
      # Identical to cri default, expect extracted message is called log, so it works with mergeKeys
      regex: '^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$'
      timeKey: time
      timeFormat: '%Y-%m-%dT%H:%M:%S.%L%z'
