---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: billing-api
  namespace: recording
spec:
  maxReplicas: 1
  minReplicas: 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-api
  namespace: recording
spec:
  replicas: 1
