---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: try
spec:
  template:
    spec:
      containers:
        - image: insightio/frontend-try
          name: try
          imagePullPolicy: Never
