---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
        - image: insightio/frontend-app
          name: app
          imagePullPolicy: Never
