FROM gradle:6.5.0-jdk14 as build

COPY build.gradle lombok.config gradle.properties settings.gradle /backend/
COPY shared/rest-elasticsearch /backend/shared/rest-elasticsearch
COPY events/model /backend/events/model
WORKDIR /backend

RUN gradle --no-daemon events:search-indexer:jar

FROM adoptopenjdk:14-jre-hotspot

COPY --from=build /backend/events/search-indexer/build/libs/search-indexer-1.0.jar /usr/app/search-indexer.jar

WORKDIR /usr/app/

CMD ["java", "-jar", "search-indexer.jar"]
