---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-api
  namespace: recording
spec:
  template:
    spec:
      containers:
        - image: docker.pkg.github.com/insights-io/Insight/session-api
          name: session-api
          imagePullPolicy: Never
