---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
        - image: docker.pkg.github.com/insights-io/Insight/frontend-app
          name: app
          imagePullPolicy: Never
