FROM gradle:6.0.1-jdk13 as build

WORKDIR /usr/src/app
COPY . /usr/src/app

RUN ./gradlew buildNative --docker-build=true

FROM registry.access.redhat.com/ubi8/ubi-minimal

WORKDIR /work
COPY --from=build /usr/src/app/target/*-runner /work/application
RUN chmod 775 /work

EXPOSE 8080
CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]