---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    team: infrastructure
spec:
  serviceName: prometheus
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
        - name: prometheus
          image: quay.io/prometheus/prometheus:v2.16.0
          args:
            - '--storage.tsdb.retention.time=14d'
            - '--storage.tsdb.path=/var/prometheus/data'
            - '--storage.tsdb.max-block-duration=2h'
            - '--storage.tsdb.min-block-duration=2h'
            - '--config.file=/etc/prometheus/shared/prometheus.yaml'
            - '--web.route-prefix=/'
            - '--web.enable-lifecycle'
          ports:
            - name: web
              containerPort: 9090
              protocol: TCP
          resources:
            requests:
              cpu: '200m'
              memory: 200Mi
            limits:
              cpu: '2000m'
              memory: 1000Mi
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/shared
              readOnly: true
            - name: prometheus-data
              mountPath: /var/prometheus/data
              subPath: prometheus-db
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9090
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 3
        - name: rules-reloader
          image: quay.io/coreos/configmap-reload:v0.0.1
          args:
            - -webhook-url=http://localhost:9090/-/reload
            - -volume-dir=/etc/prometheus/rules
            - -volume-dir=/etc/prometheus/shared
          resources:
            requests:
              cpu: '100m'
              memory: 100Mi
            limits:
              cpu: '100m'
              memory: 100Mi
          volumeMounts:
            - name: prometheus-rules
              mountPath: /etc/prometheus/rules
              readOnly: true
            - name: prometheus-config
              mountPath: /etc/prometheus/shared
              readOnly: true
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: prometheus-rules
          configMap:
            name: prometheus-rules
            optional: true
  volumeClaimTemplates:
    - metadata:
        name: prometheus-data
      spec:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: 20Gi
