---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
spec:
  template:
    spec:
      containers:
        - image: insightio/frontend-accounts
          name: accounts
          imagePullPolicy: Never
