---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beacon-api
  namespace: recording
spec:
  template:
    spec:
      containers:
        - image: insightio/beacon-api
          name: beacon-api
          imagePullPolicy: Never
