---
atlantisUrl: https://atlantis.rebrowse.dev

orgWhitelist: github.com/insights-io/*

vcsSecretName: atlantis-vcs
awsSecretName: atlantis-aws

environmentSecrets:
  - name: ATLANTIS_GH_WEBHOOK_SECRET
    secretKeyRef:
      name: github-webhook-secrets
      key: runatlantis
  - name: STRIPE_API_TOKEN
    secretKeyRef:
      name: stripe-credentials
      key: secret-key
  - name: GITHUB_TOKEN
    secretKeyRef:
      name: github-secrets
      key: personal-access-token

github:
  user: botsights

repoConfig: |
  repos:
    - id: /.*/
      workflow: authenticated
      apply_requirements: [approved, mergeable]
  workflows:
    authenticated:
      apply:
        steps:
          - run: if [ $USER_NAME != "Meemaw" ] && [ $USER_NAME != "snuderl" ]; then echo \"Sorry $USER_NAME, you are not authorized to apply.\" && exit 1; fi
          - apply

# disableApplyAll disables running `atlantis apply` without any flags
disableApplyAll: false

ingress:
  enabled: true

resources:
  requests: null
  limits: null

image:
  tag: v0.15.1
