---
backend:
  type: es
  es:
    time_key: '@ts'

image:
  fluent_bit:
    tag: 1.4.6

input:
  tail:
    memBufLimit: 200MB

parsers:
  enabled: true
  regex:
    - name: cri-2
      # Identical to cri default, expect extracted message is called log, so it works with mergeKeys
      regex: '^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$'
      timeKey: time
      timeFormat: '%Y-%m-%dT%H:%M:%S.%L%z'

tolerations:
  - key: "arm"
    operator: "Equal"
    value: "true"
    effect: "NoExecute"

