---
config:
  cookieSecret: dbgfdgfhdgfdgfdgf
  clientID: test-client-id
  clientSecret: test-client-secret

extraArgs:
  whitelist-domain: .rebrowse.dev
  cookie-domain: .rebrowse.dev
  provider: github
  github-org: meemaw-corp
  pass-user-headers: true
  pass-authorization-header: true
  set-xauthrequest: true

ingress:
  enabled: true
  path: /
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
  hosts:
    - auth.rebrowse.dev
  tls:
    - hosts:
        - auth.rebrowse.dev
      secretName: auth-rebrowse-dev-tls
