---
cfEmail: blaz.snuderl@gmail.com

infraDomain: dev.snuderls.eu
appNamespace: recording
infraNamespace: infra

fluentbitParser: cri-2

ingressAnnotationsHttps:
  cert-manager.io/cluster-issuer: letsencrypt
  kubernetes.io/ingress.class: nginx

ingressAnnotations:
  cert-manager.io/cluster-issuer: letsencrypt
  kubernetes.io/ingress.class: nginx
  nginx.ingress.kubernetes.io/auth-url: "https://auth.dev.snuderls.eu/oauth2/auth"
  nginx.ingress.kubernetes.io/auth-signin: "https://auth.dev.snuderls.eu/oauth2/start?rd=$escaped_request_uri"
  nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-User,X-Auth-Request-Email"

oauthExistingSecret: oauth2-proxy-creds
cloudflareApiKeySecretName: cloudflare-apikey-secret

storageClassName: "local-path"
