---
prometheus:
  prometheusSpec:
    replicas: 1
alertmanager:
  alertmanagerSpec:
    replicas: 1
nodeExporter:
  tolerations:
    - key: 'arm'
      operator: 'Equal'
      value: 'true'
      effect: 'NoExecute'

grafana:
  replicas: 1
