package com.meemaw.shared.sql.table;

import java.util.List;
import java.util.Map;
import org.jooq.Field;

public abstract class AbstractSqlTable {

  public abstract List<Field<?>> getInsertFields();

  public abstract List<Field<?>> getAutoGeneratedFields();

  public abstract List<Field<?>> getFields();

  public abstract Map<String, Field<?>> getFieldMappings();
}
