FROM gradle:6.4.0-jdk14 as build

COPY . /backend
WORKDIR /backend

RUN gradle auth:api:quarkusBuild --uber-jar

FROM adoptopenjdk:14-jre-hotspot

COPY --from=build /backend/auth/api/build/api-1.0-runner.jar /usr/app/service-runner.jar

WORKDIR /usr/app/

CMD ["java", "-jar", "service-runner.jar"]
