FROM gradle:6.3.0-jdk13 as build

COPY . /backend
WORKDIR /backend

RUN ./gradlew auth:api:quarkusBuild --uber-jar

FROM adoptopenjdk:13-jre-hotspot

COPY --from=build /backend/auth/api/build/api-1.0-runner.jar /usr/app/service-runner.jar

WORKDIR /usr/app/

CMD ["java", "-jar", "service-runner.jar"]
