---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  namespace: recording
spec:
  template:
    spec:
      containers:
        - image: insightio/auth-api
          name: auth-api
          env:
            - name: MAILER_MOCK
              value: true
