---
apiVersion: v1
kind: Secret
metadata:
  name: google-oauth
  namespace: recording
  labels:
    team: auth
type: Opaque
stringData:
  client_id: 237859759623-rfpiq8eo37afp0qc294ioqrjtq17q25h.apps.googleusercontent.com
  client_secret: 2e4u1VcV24Hi_UsHA0kIJIzr

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: recording
  labels:
    team: auth
type: Opaque
stringData:
  username: postgres
  password: postgres

---
apiVersion: v1
kind: Secret
metadata:
  name: mailer-configuration
  namespace: recording
  labels:
    team: auth
type: Opaque
stringData:
  username: username
  password: password
  mock: 'true'
