---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: billing-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
      labels:
        app: billing-api
        team: billing
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - image: insightio/billing-api
          imagePullPolicy: Always
          name: billing-api
          env:
            - name: JAEGER_AGENT_HOST
              value: jaeger-agent.monitoring:6831
            - name: AUTH_API_BASE_URL
              value: http://auth-api
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: stripe-webhook-signing-secrets
                  key: event
            - name: STRIPE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-credentials
                  key: api_key
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: POSTGRES_HOST
              value: postgres-postgresql
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 400Mi
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 10
      tolerations:
        - key: 'arm'
          operator: 'Equal'
          value: 'true'
          effect: 'NoExecute'
