---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: billing-api
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
spec:
  tls:
    - hosts:
        - billing-api.dev.snuderls.eu
      secretName: billing-dev-api-tls
  rules:
    - host: billing-api.dev.snuderls.eu
      http:
        paths:
          - backend:
              serviceName: billing-api
              servicePort: 80
