---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - app.rebrowse.dev
        - www.app.rebrowse.dev
      secretName: app-rebrowse-dev-tls
  rules:
    - host: app.rebrowse.dev
      http:
        paths:
          - backend:
              serviceName: app
              servicePort: 80
    - host: www.app.rebrowse.dev
      http:
        paths:
          - backend:
              serviceName: app
              servicePort: 80
