---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: session-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
      labels:
        app: session-api
        team: session
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - image: insightio/session-api
          imagePullPolicy: Always
          name: session-api
          env:
            - name: JAEGER_AGENT_HOST
              value: jaeger-agent.monitoring:6831
            - name: LOG_JSON
              value: 'true'
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: PLAINTEXT://kafka:9092
            - name: AUTH_API_BASE_URL
              value: http://auth-api
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: POSTGRES_HOST
              value: postgres-postgresql
            - name: ELASTICSEARCH_HOSTS
              value: elasticsearch-master:9200
            - name: LOCATION_LOOKUP_SERVICE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: ipstack-credentials
                  key: access-key
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 400Mi
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 10
      tolerations:
        - key: 'arm'
          operator: 'Equal'
          value: 'true'
          effect: 'NoExecute'
