---
apiVersion: batch/v1
kind: Job
metadata:
  name: session-api-migrations
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
        - image: insightio/session-api-migrations
          name: session-api-migrations
          env:
            - name: POSTGRES_HOST
              value: postgres-postgresql
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
      restartPolicy: Never
