---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: auth-api
  namespace: recording
spec:
  maxReplicas: 1
  minReplicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  namespace: recording
spec:
  replicas: 1
