---
on:
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend:test.yml'

env:
  CI: true
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Run tests 🚀
        working-directory: backend
        run: ./gradlew test --continue jacocoTestReport
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-reports
          path: backend/**/build/reports/tests/**
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: backend/**/build/reports/jacoco/test/jacocoTestReport.xml
          flags: backend
