---
on:
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend:test.yml'

env:
  CI: true
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  find_gradle_jobs:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Cache Gradle Home files
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-home-testmatrix-${{ hashFiles('**/*.gradle') }}
      - id: set-matrix
        working-directory: backend
        run: |
          TASKS=$(./gradlew --no-daemon --parallel -q testMatrix)
          echo $TASKS
          echo "::set-output name=matrix::{\"gradle_args\":$TASKS}"

  test:
    needs: find_gradle_jobs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.find_gradle_jobs.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v2
      - name: Reclaim Disk Space
        run: scripts/ci/ci-prerequisites.sh
      - name: Cache Gradle Home files
        uses: actions/cache@v2
        continue-on-error: true
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-home-${{matrix.gradle_args}}_check-${{ hashFiles('**/*.gradle') }}
      - uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Run tests (${{matrix.gradle_args}}) 🚀
        working-directory: backend
        run: |
          ./gradlew --no-daemon --continue jacocoTestReport --scan ${{matrix.gradle_args}}
        env:
          GRADLE_OPTS: -Xmx1408m
      - uses: actions/upload-artifact@v2
        if: always()
        continue-on-error: true
        with:
          name: test-reports
          path: backend/**/build/reports/tests/**
      - uses: codecov/codecov-action@v1
        continue-on-error: true
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: backend/**/build/reports/jacoco/test/jacocoTestReport.xml
          flags: backend
