---
on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  openapi:generate:
    name: Generate OpenAPI specifications
    runs-on: ubuntu-latest

    strategy:
      matrix:
        api:
          [
            { namespace: 'auth', name: 'auth-api', port: '8080' },
            { namespace: 'beacon', name: 'beacon-api', port: '8081' },
            { namespace: 'session', name: 'session-api', port: '8082' },
            { namespace: 'billing', name: 'billing-api', port: '8083' },
          ]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - run: cd backend && ./gradlew  ${{ matrix.api.namespace }}:${{ matrix.api.name }}:quarkusDev &
      - run: bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:${{ matrix.api.port }}/openapi)" != "200" ]]; do sleep 2; done'
      - run: curl http://localhost:${{ matrix.api.port }}/openapi --output ${{ matrix.api.name }}-openapi.yml
      - uses: actions/upload-artifact@v2
        with:
          name: openapi-specs
          path: '${{ matrix.api.name }}-openapi.yml'
