---
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  openapi:
    name: Openapi
    runs-on: ubuntu-latest

    strategy:
      matrix:
        api: ['auth:auth-api']

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: ${{ matrix.api }}:quarkusDev &
          build-root-directory: backend
          wrapper-directory: backend
      - run: curl http://localhost:8080/openapi --output ${{ matrix.api }}-openapi.yml
      - run: cat ${{ matrix.api }}-openapi.yml
