---
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  openapi:
    name: Openapi
    runs-on: ubuntu-latest

    strategy:
      matrix:
        api: ['auth:auth-api']

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - run: ./backend/gradlew  ${{ matrix.api }}:quarkusDev &
      - run: bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8080/openapi)" != "200" ]]; do sleep 5; done'
      - run: curl http://localhost:8080/openapi --output ${{ matrix.api }}-openapi.yml
      - run: cat ${{ matrix.api }}-openapi.yml
