---
on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend:gradle-wrapper-validation.yml'

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
