---
on:
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend:test.yml'

env:
  CI: true
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  find_gradle_jobs:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Cache Gradle Home files
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-home-testmatrix-${{ hashFiles('**/*.gradle') }}
      - id: set-matrix
        working-directory: backend
        run: |
          TASKS=$(./gradlew --no-daemon --parallel -q testMatrix)
          echo $TASKS
          echo "::set-output name=matrix::{\"gradle_args\":$TASKS}"

  test:
    needs: find_gradle_jobs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Run tests 🚀
        working-directory: backend
        run: ./gradlew test --continue jacocoTestReport
        timeout-minutes: 25
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-reports
          path: backend/**/build/reports/tests/**
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: backend/**/build/reports/jacoco/test/jacocoTestReport.xml
          flags: backend
