---
on: [push]

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  ARCHIVES: /home/runner/archives
  ARTIFACTS_PATH: frontend/app/artifacts/

jobs:
  docker_build:
    name: Docker build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [auth-api, session-api, beacon-api, billing-api, search-indexer]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}
      - name: Build docker image
        run: docker-compose -f backend/local-test-services/docker-compose.yml build ${{ matrix.target }}
      - name: Create image artifact
        run: |
          mkdir -p $ARCHIVES
          docker save local-test-services_${{ matrix.target }} > $ARCHIVES/${{ matrix.target }}.tar
      - uses: actions/upload-artifact@v2
        with:
          name: image-archives
          path: ${{ env.ARCHIVES }}

  e2e_tests:
    name: Run E2E tests
    runs-on: ubuntu-latest
    needs: [docker_build]

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: image-archives
          path: ${{ env.ARCHIVES }}
      - name: Load docker images & run containers
        working-directory: ${{ env.ARCHIVES }}
        run: |
          for file in *; do docker load < $file; done
          docker-compose -f backend/local-test-services/docker-compose.yml up auth-api session-api beacon-api billing-api search-indexer 2>&1 | tee $ARTIFACTS_PATH/docker.log &
          mkdir -p mkdir -p $ARTIFACTS_PATH
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Wait for containers & run tests
        run: |
          npx wait-on http-get://localhost:8080/health http-get://localhost:8081/health http-get://localhost:8082/health http-get://localhost:8083/health --timeout 600000
