---
on: [push]

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  ARCHIVES: /home/runner/archives

jobs:
  docker-build:
    name: Docker build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [auth-api, session-api]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}
      - run: docker-compose -f backend/local-test-services/docker-compose.yml build ${{ matrix.target }}
      - run: docker save local-test-services_${{ matrix.target }} >> $ARCHIVES/${{ matrix.target }}.tar
      - uses: actions/upload-artifact@v2
        with:
          name: image-archives
          path: ${{ env.ARCHIVES }}
