---
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

env:
  CI: true
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
  AWS_DEV_HOSTED_ZONE_ID: ${{ secrets.AWS_DEV_HOSTED_ZONE_ID }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DEV_DOMAIN_NAME: ${{ secrets.DEV_DOMAIN_NAME }}
  PR_NAME: pr-${{ github.event.number }}
  PREVIEWS_BUCKET_NAME: ${{ secrets.AWS_S3_FRONTEND_PREVIEWS_BUCKET_NAME }}

jobs:
  cleanup_preview:
    name: Cleanup preview 💣
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Delete AWS Lambda @ Edge functions
        run: |
          ./scripts/cleanup_lambda.sh "$DEFAULT_EDGE_LAMBDA_NAME"
          ./scripts/cleanup_lambda.sh "$API_EDGE_LAMBDA_NAME"
        env:
          DEFAULT_EDGE_LAMBDA_NAME: pr-852-app-default-lambda
          API_EDGE_LAMBDA_NAME: pr-852-app-api-lambda
