---
on:
  pull_request:
    paths:
      - '.github/workflows/frontend:accounts:pr:e2e.yml'
      - 'backend/**'
      - 'frontend/accounts/**'
      - 'frontend/shared/**'
      - 'jest.config.ts'
      - 'lerna.json'
      - 'package.json'
      - 'tsconfig.json'
      - 'yarn.lock'

env:
  CI: true
  ARTIFACTS_PATH: frontend/accounts/artifacts/
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  MAILER_MOCK: true

jobs:
  e2e_tests:
    name: Run Accounts E2E Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: backend | docker-compose up
        run: |
          mkdir -p $ARTIFACTS_PATH
          docker-compose -f backend/local-test-services/docker-compose.yml up auth-api 2>&1 | tee $ARTIFACTS_PATH/docker.log &
      - uses: actions/setup-node@v2
        with:
          node-version: '15.9.0'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: frontend/accounts | install
        run: yarn install --frozen-lockfile
      - name: Cache .next/cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/frontend/accounts/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}
      - name: frontend/accounts | build
        run: |
          yarn workspace @rebrowse/accounts build
      - name: frontend/accounts | start
        run: |
          yarn workspace @rebrowse/accounts start -p 3002 2>&1 | tee $ARTIFACTS_PATH/serve.log &
          node_modules/wait-on/bin/wait-on http-get://localhost:3002 --timeout 600000
          node_modules/wait-on/bin/wait-on http-get://localhost:8080/health/ready --timeout 600000
      - name: frontend/accounts | test:e2e
        run: |
          mkdir -p $ARTIFACTS_PATH/screenshots
          mkdir -p $ARTIFACTS_PATH/videos
          xvfb-run --server-args="-screen 0 1280x720x24" yarn workspace @rebrowse/accounts test:e2e
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: artifacts
          path: frontend/accounts/artifacts
