---
on:
  push:
    paths:
      - 'infrastructure/terraform/**'
      - '.github/workflows/infrastructure:terraform.yml'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.20
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: 'infrastructure/terraform'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
